FROM node:22-alpine AS builder

WORKDIR /app
COPY package*.json ./
RUN npm install

COPY . .
# On génère le client Prisma pour le build Next.js
RUN npx prisma generate

# On build l'application Next.js
RUN npm run build

FROM node:22-alpine AS runner

WORKDIR /app

ENV NODE_ENV production

COPY --from=builder /app/next.config.ts ./
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/prisma ./prisma
# Copy node_modules for prisma engine (if standalone doesn't include it fully)
COPY --from=builder /app/node_modules ./node_modules

EXPOSE 3000

ENV PORT 3000
ENV HOSTNAME "0.0.0.0"

# Commande de démarrage avec migration préalable
# On utilise le serveur standalone généré par Next.js
CMD npx prisma db push && node server.js
