FROM node:22-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# On génère le client Prisma pour le worker
RUN npx prisma generate

ENV NODE_ENV production

# Utilisation de tsx pour exécuter le worker TypeScript directement
CMD ["npx", "tsx", "src/worker/index.ts"]
