events {
    worker_connections 1024;
}

http {
    server {
        listen 80;

        # Configuration pour l'application Next.js principale
        location / {
            proxy_pass http://web:3000;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }

        # Espace réservé pour de futurs outils d'analyse (ex: Metabase, Grafana)
        # location /analytics {
        #     proxy_pass http://analytics:3000;
        # }
    }
}
